apiVersion: apps/v1
kind: Deployment
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            app: youtext-services
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: youtext-services
        spec:
            containers:
                - env:
                      - name: OPENAI_API_KEY
                        value:
                      - name: OPENAI_MODEL
                        value:
                      - name: IPFS_INFURA_URL
                        value:
                      - name: FIREBASE_API_KEY
                        value:
                      - name: FIREBASE_AUTH_DOMAIN
                        value:
                      - name: FIREBASE_PROJECT_ID
                        value:
                      - name: FIREBASE_STORAGE_BUCKET
                        value:
                      - name: FIREBASE_MESSAGING_SENDER_ID
                        value:
                      - name: FIREBASE_APP_ID
                        value:
                      - name: FIREBASE_MEASUREMENT_ID
                        value:
                  image:
                  imagePullPolicy: IfNotPresent
                  name: youtext-services
                  ports:
                      - containerPort: 3000
                        protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
status:
    availableReplicas: 1
    conditions:
        - lastTransitionTime: '2023-08-12T15:17:10Z'
          lastUpdateTime: '2023-08-12T15:24:36Z'
          message: ReplicaSet "youtext-services-6894449d87" has successfully progressed.
          reason: NewReplicaSetAvailable
          status: 'True'
          type: Progressing
        - lastTransitionTime: '2023-10-30T21:49:34Z'
          lastUpdateTime: '2023-10-30T21:49:34Z'
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: 'True'
          type: Available
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
